-- MySQL Script generated by MySQL Workbench
-- Mon Aug  8 14:18:32 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` DEFAULT CHARACTER SET utf8 ;
USE `main` ;

-- -----------------------------------------------------
-- Table `main`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`user` ;

CREATE TABLE IF NOT EXISTS `main`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(256) NOT NULL,
  `address2` VARCHAR(10) NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `date_birth` DATE NULL,
  `gender` VARCHAR(45) NULL,
  `password` VARCHAR(256) NOT NULL,
  `date_creation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT 0,
  `document_type` VARCHAR(45) NULL,
  `document_number` VARCHAR(256) NULL,
  `document_image` VARCHAR(1024) NULL,
  `active` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `main`.`login_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`login_log` ;

CREATE TABLE IF NOT EXISTS `main`.`login_log` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `username` VARCHAR(145) NULL,
  `date` TIMESTAMP NULL,
  `server` VARCHAR(60) NULL,
  `client_ip` VARCHAR(45) NULL,
  `user_agent` VARCHAR(120) NULL,
  `token` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_login_log_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_login_log_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `main`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
